[tool.poetry]
name = "sansio-lsp-client"
version = "0.1.0"
description = """
An implementation of the client side of the LSP protocol, useful for \
mbedding easily in your editor.\
"""
authors = ["Purple Myst <PurpleMyst@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.dev-dependencies]

[tool.black]
line-length = 79
py36 = true
